import input from "./input.hbs";
import message from "./message.hbs";
import avatar from "./avatar.hbs";
import addMessageLine from "./addMessageLine.hbs";
import friendInfoTopLine from "./friendInfoTopLine.hbs";
import searchIcon from "./searchIcon.hbs";
import arrowIcon from "./arrowIcon.hbs";
import clipIcon from "./clipIcon.hbs";
import noPhotoIcon from "./noPhotoIcon.hbs";
import dottesIcon from "./dottesIcon.hbs";
import Handlebars from "handlebars/dist/handlebars.runtime";

Handlebars.registerPartial('inputItem', input);
Handlebars.registerPartial('messageItem', message);
Handlebars.registerPartial('avatarItem', avatar);
Handlebars.registerPartial('addMessageLine', addMessageLine);
Handlebars.registerPartial('friendInfoTopLine', friendInfoTopLine);
Handlebars.registerPartial('searchIcon', searchIcon);
Handlebars.registerPartial('arrowIcon', arrowIcon);
Handlebars.registerPartial('clipIcon', clipIcon);
Handlebars.registerPartial('noPhotoIcon', noPhotoIcon);
Handlebars.registerPartial('dottesIcon', dottesIcon);